package com.papercube.yala.DB.helper;

import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;

import com.papercube.yala.Model.Figura.Figura;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by Hudeya on 31/03/2018.
 */

public class DatabaseHelper extends SQLiteOpenHelper {


    private static final int DATABASE_VERSION = 1;

    // Database Name
    private static final String DATABASE_NAME = "yalaManager";

    // Table Names
    private static final String TABLE_ALBUM = "album";

    // album Table - column names
    private static final String KEY_FIGURA = "figura";
    private static final String KEY_NOMBRE = "nombre";
    private static final String KEY_CANTIDAD = "cantidad";
    private static final String KEY_PAIS = "pais";
    private static final String KEY_TIPO = "tipo";

    private static  final String CREATE_TABLE_ALBUM = "CREATE TABLE "+ TABLE_ALBUM+ "("+KEY_FIGURA+ " INT, "+
            KEY_NOMBRE+" TEXT," + KEY_CANTIDAD+ " INT," +KEY_PAIS+ " TEXT,"+KEY_TIPO+ " TEXT"+")";

    private static  final String INSERT_ROW = "("+KEY_FIGURA+", "+KEY_NOMBRE+", "+KEY_CANTIDAD+", "+KEY_PAIS+", "+KEY_TIPO+")";





    public DatabaseHelper(Context context) {
        super(context, DATABASE_NAME, null, DATABASE_VERSION);
    }


    @Override
    public void onCreate(SQLiteDatabase db) {
        //Creando tabla MARCA
        db.execSQL(CREATE_TABLE_ALBUM);
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (0,'Panini Logo',0,'Panini','Especial')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (1,'FIFA Logo',0,'Panini','Especial')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (2,'World Cup Trophy',0,'Panini','Especial')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (3,'2018 World Cup Graphic 1',0,'Panini','Especial')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (4,'2018 World Cup Graphic 2',0,'Panini','Especial')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (5,'2018 World Cup Logo 1',0,'Panini','Especial')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (6,'2018 World Cup Logo 2',0,'Panini','Especial')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (7,'Official Ball',0,'Panini','Especial')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (8,'Ekaterinburg Arena',0,'Stadiums','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (9,'Kaliningrad Stadium',0,'Stadiums','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (10,'Kazan Arena',0,'Stadiums','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (11,'Spartak Stadium',0,'Stadiums','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (12,'Nizhny Novgorod Stadium',0,'Stadiums','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (13,'Luzhniki Stadium',0,'Stadiums','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (14,'Rostov Arena',0,'Stadiums','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (15,'Saint Petersburg Stadium',0,'Stadiums','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (16,'Samara Arena',0,'Stadiums','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (17,'Mordovia Arena',0,'Stadiums','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (18,'Fisht Stadium',0,'Stadiums','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (19,'Volgograd Arena',0,'Stadiums','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (20,'Logo Russia',0,'Russia','Especial')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (21,'Team Russia',0,'Russia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (22,'Igor Akinfeev',0,'Russia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (23,'Igor Smolnikov',0,'Russia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (24,'Viktor Vasin',0,'Russia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (25,'Mário Fernandes',0,'Russia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (26,'Fedor Kudryashov',0,'Russia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (27,'Ilya Kutepov',0,'Russia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (28,'Dmitri Kombarov',0,'Russia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (29,'Aleksei Miranchuk',0,'Russia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (30,'Denis Glushakov',0,'Russia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (31,'Aleksandr Golovin',0,'Russia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (32,'Yuri Zhirkov',0,'Russia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (33,'Aleksandr Samedov',0,'Russia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (34,'Aleksandr Erokhin',0,'Russia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (35,'Alan Dzagoev',0,'Russia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (36,'Daler Kuzyayev',0,'Russia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (37,'Dmitry Poloz',0,'Russia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (38,'Fedor Smolov',0,'Russia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (39,'Aleksandr Kokorin',0,'Russia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (40,'Logo Saudi Arabia',0,'Saudi Arabia','Especial')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (41,'Team Saudi Arabia',0,'Saudi Arabia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (42,'Abdullah Al-Mayouf',0,'Saudi Arabia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (43,'Osama Hawsawi',0,'Saudi Arabia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (44,'Abdullah Al-Zori',0,'Saudi Arabia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (45,'Mansoor Al-Harbi',0,'Saudi Arabia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (46,'Omar Hawsawi',0,'Saudi Arabia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (47,'Yasser Al-Shahrani',0,'Saudi Arabia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (48,'Motaz Hawsawi',0,'Saudi Arabia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (49,'Mohammed Al-Breik',0,'Saudi Arabia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (50,'Taisir Al-Jassim',0,'Saudi Arabia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (51,'Salman Al-Faraj',0,'Saudi Arabia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (52,'Abdulmalek Al-Khaibri',0,'Saudi Arabia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (53,'Salman Al-Moasher',0,'Saudi Arabia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (54,'Yahya Al-Shehri',0,'Saudi Arabia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (55,'Salem Al-Dawsari',0,'Saudi Arabia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (56,'Nawaf Al-Abed',0,'Saudi Arabia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (57,'Mohammad Al-Sahlawi',0,'Saudi Arabia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (58,'Nasser Al-Shamrani',0,'Saudi Arabia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (59,'Fahad Al-Muwallad',0,'Saudi Arabia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (60,'Logo Egypt',0,'Egypt','Especial')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (61,'Team Egypt',0,'Egypt','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (62,'Essam El Hadary',0,'Egypt','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (63,'Ali Gabr',0,'Egypt','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (64,'Ahmed El Mohamady',0,'Egypt','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (65,'Omar Gaber',0,'Egypt','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (66,'Ramy Rabia',0,'Egypt','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (67,'Ahmed Hegazi',0,'Egypt','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (68,'Ahmed Abdelmonem Fathy',0,'Egypt','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (69,'Mohamed Abdel Shafy',0,'Egypt','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (70,'Saad Samir',0,'Egypt','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (71,'Tarek Hamed',0,'Egypt','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (72,'Mahmoud Kahraba',0,'Egypt','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (73,'Mohamed Elneny',0,'Egypt','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (74,'Mahmoud Trezeguet',0,'Egypt','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (75,'Abdallah Said',0,'Egypt','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (76,'Ramadan Sobhi',0,'Egypt','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (77,'Ahmed Hassan',0,'Egypt','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (78,'Mohamed Salah',0,'Egypt','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (79,'Amr Gamal',0,'Egypt','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (80,'Logo Uruguay',0,'Uruguay','Especial')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (81,'Team Uruguay',0,'Uruguay','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (82,'Fernando Muslera',0,'Uruguay','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (83,'Maxi Pereira',0,'Uruguay','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (84,'Diego Godin',0,'Uruguay','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (85,'Martin Caceres',0,'Uruguay','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (86,'Jose Gimenez',0,'Uruguay','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (87,'Sebastian Coates',0,'Uruguay','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (88,'Gaston Silva',0,'Uruguay','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (89,'Mathias Corujo',0,'Uruguay','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (90,'Egidio Arevalo Rios',0,'Uruguay','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (91,'Alvaro Gonzalez',0,'Uruguay','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (92,'Nicolas Lodeiro',0,'Uruguay','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (93,'Carlos Sanchez',0,'Uruguay','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (94,'Cristian Rodriguez',0,'Uruguay','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (95,'Matias Vecino',0,'Uruguay','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (96,'Edinson Cavani',0,'Uruguay','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (97,'Luis Suarez',0,'Uruguay','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (98,'Cristhian Stuani',0,'Uruguay','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (99,'Diego Rolan',0,'Uruguay','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (100,'Logo Portugal',0,'Portugal','Especial')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (101,'Team Portugal',0,'Portugal','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (102,'Rui Patricio',0,'Portugal','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (103,'Bruno Alves',0,'Portugal','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (104,'Pepe',0,'Portugal','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (105,'Jose Fonte',0,'Portugal','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (106,'Eliseu',0,'Portugal','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (107,'Cedric',0,'Portugal','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (108,'Raphael Guerreiro',0,'Portugal','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (109,'Joao Moutinho',0,'Portugal','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (110,'Joao Mario',0,'Portugal','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (111,'Danilo Pereira',0,'Portugal','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (112,'William Carvalho',0,'Portugal','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (113,'Andre Gomes',0,'Portugal','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (114,'Ricardo Quaresma',0,'Portugal','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (115,'Bernardo Silva',0,'Portugal','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (116,'Andre Silva',0,'Portugal','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (117,'Gelson Martins',0,'Portugal','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (118,'Cristiano Ronaldo',0,'Portugal','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (119,'Nani',0,'Portugal','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (120,'Logo Spain',0,'Spain','Especial')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (121,'Team Spain',0,'Spain','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (122,'David de Gea',0,'Spain','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (123,'Jordi Alba',0,'Spain','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (124,'Nacho',0,'Spain','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (125,'Nacho Monreal',0,'Spain','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (126,'Gerard Pique',0,'Spain','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (127,'Sergio Ramos',0,'Spain','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (128,'Daniel Carvajal',0,'Spain','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (129,'Sergio Busquets',0,'Spain','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (130,'Thiago',0,'Spain','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (131,'Isco',0,'Spain','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (132,'Koke',0,'Spain','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (133,'Marco Asensio',0,'Spain','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (134,'Andrés Iniesta',0,'Spain','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (135,'David Villa',0,'Spain','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (136,'Saul Niguez',0,'Spain','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (137,'Alvaro Morata',0,'Spain','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (138,'Vitolo',0,'Spain','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (139,'Diego Costa',0,'Spain','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (140,'Logo Morocco',0,'Morocco','Especial')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (141,'Team Morocco',0,'Morocco','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (142,'Munir Mohamedi',0,'Morocco','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (143,'Medhi Benatia',0,'Morocco','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (144,'Nabil Dirar',0,'Morocco','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (145,'Romain Saiss',0,'Morocco','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (146,'Fouad Chafik',0,'Morocco','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (147,'Hamza Mendyl',0,'Morocco','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (148,'Achraf Hakimi',0,'Morocco','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (149,'Mbark Boussoufa',0,'Morocco','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (150,'Karim El Ahmadi',0,'Morocco','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (151,'Younes Belhanda',0,'Morocco','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (152,'Nordin Amrabat',0,'Morocco','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (153,'Faycal Fajr',0,'Morocco','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (154,'Hakim Ziyech',0,'Morocco','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (155,'Youssef Ait Bennasser',0,'Morocco','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (156,'Khalid Boutaib',0,'Morocco','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (157,'Rachid Alioui',0,'Morocco','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (158,'Aziz Bouhaddouz',0,'Morocco','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (159,'Youssef En-Nesyri',0,'Morocco','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (160,'Logo Iran',0,'Iran','Especial')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (161,'Team Iran',0,'Iran','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (162,'Alireza Beiranvand',0,'Iran','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (163,'Pejman Montazeri',0,'Iran','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (164,'Vouria Ghafouri',0,'Iran','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (165,'Jalal Hosseini',0,'Iran','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (166,'Milad Mohammadi',0,'Iran','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (167,'Morteza Pouraliganji',0,'Iran','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (168,'Ramin Rezaeian',0,'Iran','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (169,'Ehsan Hajsafi',0,'Iran','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (170,'Omid Ebrahimi',0,'Iran','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (171,'Saeid Ezatolahi',0,'Iran','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (172,'Vahid Amiri',0,'Iran','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (173,'Alireza Jahanbakhsh',0,'Iran','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (174,'Ashkan Dejagah',0,'Iran','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (175,'Saman Ghoddos',0,'Iran','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (176,'Mehdi Taremi',0,'Iran','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (177,'Karim Ansarifard',0,'Iran','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (178,'Reza Ghoochannejhad',0,'Iran','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (179,'Sardar Azmoun',0,'Iran','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (180,'Logo France',0,'France','Especial')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (181,'Team France',0,'France','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (182,'Hugo Lloris',0,'France','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (183,'Raphael Varane',0,'France','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (184,'Lucas Digne',0,'France','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (185,'Djibril Sidibe',0,'France','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (186,'Samuel Umtiti',0,'France','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (187,'Layvin Kurzawa',0,'France','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (188,'Laurent Koscielny',0,'France','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (189,'Blaise Matuidi',0,'France','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (190,'N Golo Kante',0,'France','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (191,'Thomas Lemar',0,'France','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (192,'Adrien Rabiot',0,'France','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (193,'Paul Pogba',0,'France','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (194,'Olivier Giroud',0,'France','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (195,'Antoine Griezmann',0,'France','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (196,'Alexandre Lacazette',0,'France','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (197,'Kylian Mbappe',0,'France','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (198,'Ousmane Dembele',0,'France','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (199,'Anthony Martial',0,'France','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (200,'Logo Australia',0,'Australia','Especial')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (201,'Team Australia',0,'Australia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (202,'Mathew Ryan',0,'Australia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (203,'Mitchell Langerak',0,'Australia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (204,'Milos Degenek',0,'Australia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (205,'Bailey Wright',0,'Australia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (206,'Aziz Behich',0,'Australia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (207,'Trent Sainsbury',0,'Australia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (208,'Ryan McGowan',0,'Australia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (209,'Mark Milligan',0,'Australia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (210,'Aaron Mooy',0,'Australia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (211,'James Troisi',0,'Australia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (212,'Mile Jedinak',0,'Australia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (213,'Massimo Luongo',0,'Australia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (214,'Jackson Irvine',0,'Australia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (215,'Tom Rogic',0,'Australia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (216,'Tim Cahill',0,'Australia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (217,'Mathew Leckie',0,'Australia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (218,'Tomi Juric',0,'Australia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (219,'Robbie Kruse',0,'Australia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (220,'Logo Peru',0,'Peru','Especial')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (221,'Team Peru',0,'Peru','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (222,'Pedro Gallese',0,'Peru','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (223,'Carlos Caceda',0,'Peru','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (224,'Aldo Corzo',0,'Peru','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (225,'Miguel Trauco',0,'Peru','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (226,'Christian Ramos',0,'Peru','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (227,'Luis Advincula',0,'Peru','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (228,'Alberto Rodriguez',0,'Peru','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (229,'Miguel Araujo',0,'Peru','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (230,'Christian Cueva',0,'Peru','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (231,'Renato Tapia',0,'Peru','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (232,'Andy Polo',0,'Peru','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (233,'Yoshimar Yotun',0,'Peru','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (234,'Edison Flores',0,'Peru','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (235,'Paolo Hurtado',0,'Peru','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (236,'Paolo Guerrero',0,'Peru','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (237,'Jefferson Farfan',0,'Peru','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (238,'Raul Ruidiaz',0,'Peru','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (239,'André Carrillo',0,'Peru','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (240,'Logo Denmark',0,'Denmark','Especial')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (241,'Team Denmark',0,'Denmark','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (242,'Kasper Schmeichel',0,'Denmark','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (243,'Jannik Vestergaard',0,'Denmark','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (244,'Simon Kjaer',0,'Denmark','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (245,'Andreas Christensen',0,'Denmark','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (246,'Andreas Bjelland',0,'Denmark','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (247,'Mathias Jorgensen',0,'Denmark','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (248,'Jens Stryger Larsen',0,'Denmark','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (249,'Peter Ankersen',0,'Denmark','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (250,'Riza Durmisi',0,'Denmark','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (251,'William Kvist',0,'Denmark','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (252,'Thomas Delaney',0,'Denmark','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (253,'Christian Eriksen',0,'Denmark','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (254,'Lasse Schone',0,'Denmark','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (255,'Pione Sisto',0,'Denmark','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (256,'Nicklas Bendtner',0,'Denmark','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (257,'Nicolai Jorgensen',0,'Denmark','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (258,'Yussuf Poulsen',0,'Denmark','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (259,'Andreas Cornelius',0,'Denmark','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (260,'Logo Argentina',0,'Argentina','Especial')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (261,'Team Argentina',0,'Argentina','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (262,'Sergio Romero',0,'Argentina','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (263,'Gabriel Mercado',0,'Argentina','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (264,'Federico Fazio',0,'Argentina','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (265,'Javier Mascherano',0,'Argentina','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (266,'Nicolas Otamendi',0,'Argentina','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (267,'Marcos Rojo',0,'Argentina','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (268,'Ramiro Funes Mori',0,'Argentina','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (269,'Lucas Biglia',0,'Argentina','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (270,'Enzo Perez',0,'Argentina','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (271,'Ángel Di Maria',0,'Argentina','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (272,'Marcos Acuna',0,'Argentina','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (273,'Ever Banega',0,'Argentina','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (274,'Eduardo Salvio',0,'Argentina','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (275,'Mauro Icardi',0,'Argentina','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (276,'Lionel Messi',0,'Argentina','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (277,'Paulo Dybala',0,'Argentina','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (278,'Sergio Aguero',0,'Argentina','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (279,'Gonzalo Higuain',0,'Argentina','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (280,'Logo Iceland',0,'Iceland','Especial')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (281,'Team Iceland',0,'Iceland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (282,'Hannes Halldorsson',0,'Iceland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (283,'Birkir Saevarsson',0,'Iceland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (284,'Ragnar Sigurosson',0,'Iceland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (285,'Kari Arnason',0,'Iceland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (286,'Ari Skulason',0,'Iceland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (287,'Sverrir Ingason',0,'Iceland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (288,'Hordur Magnusson',0,'Iceland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (289,'Aron Gunnarsson',0,'Iceland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (290,'Birkir Bjarnason',0,'Iceland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (291,'Emil Hallfredsson',0,'Iceland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (292,'Gylfi Sigurdsson',0,'Iceland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (293,'Arnor Ingvi Traustason',0,'Iceland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (294,'Rurik Gislason',0,'Iceland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (295,'Johann Gudmundsson',0,'Iceland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (296,'Alfred Finnbogason',0,'Iceland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (297,'Jon Dadi Bodvarsson',0,'Iceland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (298,'Vidar Orn Kjartansson',0,'Iceland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (299,'Bjorn Sigurdarson',0,'Iceland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (300,'Logo Croatia',0,'Croatia','Especial')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (301,'Team Croatia',0,'Croatia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (302,'Danijel Subasic',0,'Croatia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (303,'Sime Vrsaljko',0,'Croatia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (304,'Ivan Strinic',0,'Croatia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (305,'Dejan Lovren',0,'Croatia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (306,'Domagoj Vida',0,'Croatia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (307,'Josip Pivaric',0,'Croatia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (308,'Vedran Corluka',0,'Croatia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (309,'Ivan Rakitic',0,'Croatia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (310,'Luka Modric',0,'Croatia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (311,'Marcelo Brozovic',0,'Croatia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (312,'Marko Rog',0,'Croatia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (313,'Mario Pasalic',0,'Croatia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (314,'Milan Badelj',0,'Croatia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (315,'Mateo Kovacic',0,'Croatia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (316,'Andrej Kramaric',0,'Croatia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (317,'Nikola Kalinic',0,'Croatia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (318,'Mario Mandzukic',0,'Croatia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (319,'Ivan Perisic',0,'Croatia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (320,'Logo Nigeria',0,'Nigeria','Especial')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (321,'Team Nigeria',0,'Nigeria','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (322,'Ikechukwu Ezenwa',0,'Nigeria','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (323,'Elderson Echiejile',0,'Nigeria','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (324,'Shehu Abdullahi',0,'Nigeria','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (325,'William Troos',0,'Nigeria','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (326,'Leon Balogun',0,'Nigeria','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (327,'Kenneth Omeruo',0,'Nigeria','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (328,'Ola Aina',0,'Nigeria','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (329,'John Obi Mikel',0,'Nigeria','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (330,'Ogenyi Onazi',0,'Nigeria','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (331,'Etebo Oghenekaro',0,'Nigeria','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (332,'Wilfred Ndidi',0,'Nigeria','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (333,'Mikel Agu',0,'Nigeria','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (334,'Ahmed Musa',0,'Nigeria','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (335,'Victor Moses',0,'Nigeria','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (336,'Moses Simon',0,'Nigeria','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (337,'Odion Ighalo',0,'Nigeria','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (338,'Alex Iwobi',0,'Nigeria','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (339,'Kelechi Iheanacho',0,'Nigeria','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (340,'Logo Brazil',0,'Brazil','Especial')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (341,'Team Brazil',0,'Brazil','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (342,'Alisson',0,'Brazil','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (343,'Dani Alves',0,'Brazil','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (344,'Thiago Silva',0,'Brazil','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (345,'Miranda',0,'Brazil','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (346,'Filipe Luís',0,'Brazil','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (347,'Marquinhos',0,'Brazil','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (348,'Marcelo',0,'Brazil','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (349,'Willian',0,'Brazil','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (350,'Paulinho',0,'Brazil','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (351,'Fernandinho',0,'Brazil','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (352,'Casemiro',0,'Brazil','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (353,'Renato Augusto',0,'Brazil','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (354,'Giuliano',0,'Brazil','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (355,'Philippe Coutinho',0,'Brazil','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (356,'Douglas Costa',0,'Brazil','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (357,'Roberto Firmino',0,'Brazil','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (358,'Gabriel Jesus',0,'Brazil','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (359,'Neymar Jr',0,'Brazil','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (360,'Logo Switzerland',0,'Switzerland','Especial')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (361,'Team Switzerland',0,'Switzerland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (362,'Yann Sommer',0,'Switzerland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (363,'Stephan Lichtsteiner',0,'Switzerland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (364,'Manuel Akanji',0,'Switzerland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (365,'Michael Lang',0,'Switzerland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (366,'Ricardo Rodriguez',0,'Switzerland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (367,'Johan Djourou',0,'Switzerland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (368,'Fabian Schar',0,'Switzerland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (369,'Granit Xhaka',0,'Switzerland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (370,'Steven Zuber',0,'Switzerland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (371,'Blerim Dzemaili',0,'Switzerland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (372,'Denis Zakaria',0,'Switzerland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (373,'Xherdan Shaqiri',0,'Switzerland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (374,'Valon Behrami',0,'Switzerland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (375,'Gelson Fernandes',0,'Switzerland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (376,'Breel Embolo',0,'Switzerland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (377,'Haris Seferovic',0,'Switzerland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (378,'Admir Mehmedi',0,'Switzerland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (379,'Eren Derdiyok',0,'Switzerland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (380,'Logo Costa Rica',0,'Costa Rica','Especial')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (381,'Team Costa Rica',0,'Costa Rica','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (382,'Keylor Navas',0,'Costa Rica','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (383,'Giancarlo Gonzalez',0,'Costa Rica','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (384,'Cristian Gamboa',0,'Costa Rica','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (385,'Bryan Oviedo',0,'Costa Rica','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (386,'Francisco Calvo',0,'Costa Rica','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (387,'Kendall Waston',0,'Costa Rica','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (388,'Ronald Matarrita',0,'Costa Rica','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (389,'Michael Umana',0,'Costa Rica','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (390,'Johnny Acosta',0,'Costa Rica','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (391,'Bryan Ruiz',0,'Costa Rica','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (392,'Celso Borges',0,'Costa Rica','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (393,'Christian Bolanos',0,'Costa Rica','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (394,'Randall Azofeifa',0,'Costa Rica','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (395,'David Guzman',0,'Costa Rica','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (396,'Rodney Wallace',0,'Costa Rica','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (397,'Joel Campbell',0,'Costa Rica','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (398,'Marco Urena',0,'Costa Rica','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (399,'Johan Venegas',0,'Costa Rica','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (400,'Logo Serbia',0,'Serbia','Especial')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (401,'Team Serbia',0,'Serbia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (402,'Vladimir Stojkovic',0,'Serbia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (403,'Branislav Ivanovic',0,'Serbia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (404,'Aleksandar Kolarov',0,'Serbia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (405,'Antonio Rukavina',0,'Serbia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (406,'Matija Nastasic',0,'Serbia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (407,'Dusko Tosic',0,'Serbia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (408,'Nikola Maksimovic',0,'Serbia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (409,'Jagos Vukovic',0,'Serbia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (410,'Dusan Tadic',0,'Serbia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (411,'Sergej Milinkovic-Savic',0,'Serbia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (412,'Nemanja Matic',0,'Serbia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (413,'Luka Milivojevic',0,'Serbia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (414,'Adem Ljajic',0,'Serbia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (415,'Nemanja Gudelj',0,'Serbia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (416,'Mijat Gacinovic',0,'Serbia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (417,'Filip Kostic',0,'Serbia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (418,'Aleksandar Mitrovic',0,'Serbia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (419,'Aleksandar Prijovic',0,'Serbia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (420,'Logo Germany',0,'Germany ','Especial')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (421,'Team Germany',0,'Germany ','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (422,'Manuel Neuer',0,'Germany ','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (423,'Mats Hummels',0,'Germany ','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (424,'Antonio Rudiger',0,'Germany ','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (425,'Jerome Boateng',0,'Germany ','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (426,'Joshua Kimmich',0,'Germany ','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (427,'Jonas Hector',0,'Germany ','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (428,'Julian Draxler',0,'Germany ','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (429,'Toni Kroos',0,'Germany ','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (430,'Emre Can',0,'Germany ','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (431,'Leon Goretzka',0,'Germany ','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (432,'Julian Brandt',0,'Germany ','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (433,'Sebastian Rudy',0,'Germany ','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (434,'Leroy Sane',0,'Germany ','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (435,'Mesut Ozil',0,'Germany ','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (436,'Sami Khedira',0,'Germany ','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (437,'Mario Gotze',0,'Germany ','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (438,'Thomas Muller',0,'Germany ','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (439,'Timo Werner',0,'Germany ','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (440,'Logo Mexico',0,'Mexico','Especial')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (441,'Team Mexico',0,'Mexico','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (442,'Guillermo Ochoa',0,'Mexico','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (443,'Hugo Ayala',0,'Mexico','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (444,'Diego Reyes',0,'Mexico','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (445,'Hector Moreno',0,'Mexico','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (446,'Jesús Gallardo',0,'Mexico','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (447,'Miguel Layun',0,'Mexico','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (448,'Carlos Salcedo',0,'Mexico','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (449,'Jonathan dos Santos',0,'Mexico','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (450,'Giovani dos Santos',0,'Mexico','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (451,'Andrés Guardado',0,'Mexico','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (452,'Héctor Herrera',0,'Mexico','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (453,'Javier Aquino',0,'Mexico','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (454,'Jesus Corona',0,'Mexico','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (455,'Hirving Lozano',0,'Mexico','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (456,'Raul Jimenez',0,'Mexico','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (457,'Carlos Vela',0,'Mexico','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (458,'Javier Hernandez',0,'Mexico','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (459,'Oribe Peralta',0,'Mexico','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (460,'Logo Sweden',0,'Sweden','Especial')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (461,'Team Sweden',0,'Sweden','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (462,'Robin Olsen',0,'Sweden','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (463,'Mikael Lustig',0,'Sweden','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (464,'Victor Nilsson Lindelof',0,'Sweden','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (465,'Andreas Granqvist',0,'Sweden','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (466,'Martin Olsson',0,'Sweden','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (467,'Ludwig Augustinsson',0,'Sweden','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (468,'Emil Krafth',0,'Sweden','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (469,'Pontus Jansson',0,'Sweden','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (470,'Sebastian Larsson',0,'Sweden','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (471,'Emil Forsberg',0,'Sweden','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (472,'Gustav Svensson',0,'Sweden','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (473,'Viktor Claesson',0,'Sweden','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (474,'Jimmy Durmaz',0,'Sweden','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (475,'Albin Ekdal',0,'Sweden','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (476,'Isaac Kiese Thelin',0,'Sweden','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (477,'Marcus Berg',0,'Sweden','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (478,'John Guidetti',0,'Sweden','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (479,'Ola Toivonen',0,'Sweden','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (480,'Logo Korea Republic',0,'Korea Republic','Especial')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (481,'Team Korea Republic',0,'Korea Republic','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (482,'Kim Seun',0,'Korea Republic','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (483,'Kim Youn',0,'Korea Republic','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (484,'Kim Ji',0,'Korea Republic','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (485,'Kwak Ta',0,'Korea Republic','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (486,'Hong Jeon',0,'Korea Republic','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (487,'Jang Hyu',0,'Korea Republic','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (488,'Koo J',0,'Korea Republic','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (489,'Kwon Chan',0,'Korea Republic','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (490,'Ki Sun',0,'Korea Republic','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (491,'Nam Ta',0,'Korea Republic','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (492,'Han Koo',0,'Korea Republic','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (493,'Lee Chun',0,'Korea Republic','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (494,'Jung Wo',0,'Korea Republic','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (495,'Lee Ja',0,'Korea Republic','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (496,'Son Heun',0,'Korea Republic','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (497,'Ji Don',0,'Korea Republic','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (498,'Kim Shi',0,'Korea Republic','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (499,'Hwang He',0,'Korea Republic','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (500,'Logo Belgium',0,'Belgium','Especial')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (501,'Team Belgium',0,'Belgium','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (502,'Thibaut Courtois',0,'Belgium','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (503,'Toby Alderweireld',0,'Belgium','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (504,'Thomas Vermaelen',0,'Belgium','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (505,'Jan Vertonghen',0,'Belgium','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (506,'Vincent Kompany',0,'Belgium','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (507,'Thomas Meunier',0,'Belgium','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (508,'Axel Witsel',0,'Belgium','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (509,'Radja Nainggolan',0,'Belgium','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (510,'Kevin De Bruyne',0,'Belgium','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (511,'Marouane Fellaini',0,'Belgium','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (512,'Youri Tielemans',0,'Belgium','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (513,'Mousa Dembel',0,'Belgium','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (514,'Nacer Chadli',0,'Belgium','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (515,'Eden Hazard',0,'Belgium','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (516,'Yannick Carrasco',0,'Belgium','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (517,'Dries Mertens',0,'Belgium','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (518,'Michy Batshuayi',0,'Belgium','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (519,'Romelu Lukaku',0,'Belgium','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (520,'Logo Panama',0,'Panama','Especial')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (521,'Team Panama',0,'Panama','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (522,'Jaime Penedo',0,'Panama','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (523,'Jose Calderon',0,'Panama','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (524,'Michael Murillo',0,'Panama','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (525,'Fidel Escobar',0,'Panama','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (526,'Roman Torres',0,'Panama','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (527,'Adolfo Machado',0,'Panama','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (528,'Eric Davis',0,'Panama','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (529,'Luis Ovalle',0,'Panama','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (530,'Felipe Baloy',0,'Panama','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (531,'Gabriel Gomez',0,'Panama','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (532,'Edgar Barcenas',0,'Panama','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (533,'Armando Cooper',0,'Panama','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (534,'Alberto Quintero',0,'Panama','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (535,'Aníbal Godoy',0,'Panama','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (536,'Blas Perez',0,'Panama','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (537,'Gabriel Torres',0,'Panama','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (538,'Luis Tejada',0,'Panama','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (539,'Abdiel Arroyo',0,'Panama','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (540,'Logo Tunisia',0,'Tunisia','Especial')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (541,'Team Tunisia',0,'Tunisia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (542,'Aymen Mathlouthi',0,'Tunisia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (543,'Ali Maaloul',0,'Tunisia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (544,'Syam Ben Youssef',0,'Tunisia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (545,'Aymen Abdennour',0,'Tunisia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (546,'Hamdi Nagguez',0,'Tunisia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (547,'Yassine Meriah',0,'Tunisia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (548,'Oussama Haddadi',0,'Tunisia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (549,'Ferjani Sassi',0,'Tunisia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (550,'Wahbi Khazri',0,'Tunisia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (551,'Mohamed Amine Ben Amor',0,'Tunisia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (552,'Ghailene Chaalali',0,'Tunisia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (553,'Naim Sliti',0,'Tunisia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (554,'Youssef Msakni',0,'Tunisia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (555,'Fakhreddine Ben Youssef',0,'Tunisia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (556,'Taha Yassine Khenissi',0,'Tunisia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (557,'Yoann Touzghar',0,'Tunisia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (558,'Anice Badri',0,'Tunisia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (559,'Ahmed Akaichi',0,'Tunisia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (560,'Team Logo',0,'England','Especial')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (561,'Team Photo',0,'England','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (562,'Joe Hart',0,'England','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (563,'Jordan Pickford',0,'England','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (564,'Gary Cahill',0,'England','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (565,'Kyle Walker',0,'England','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (566,'John Stones',0,'England','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (567,'Ryan Bertrand',0,'England','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (568,'Danny Rose',0,'England','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (569,'Phil Jones',0,'England','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (570,'Jordan Henderson',0,'England','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (571,'Alex Oxlad',0,'England','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (572,'Dele Alli',0,'England','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (573,'Eric Dier',0,'England','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (574,'Adam Lallana',0,'England','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (575,'Jesse Lingard',0,'England','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (576,'Raheem Sterling',0,'England','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (577,'Harry Kane',0,'England','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (578,'Marcus Rashford',0,'England','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (579,'Jamie Vardy',0,'England','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (580,'Logo Poland',0,'Poland','Especial')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (581,'Team Poland',0,'Poland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (582,'Lukasz Fabianski',0,'Poland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (583,'Wojciech Szczesny',0,'Poland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (584,'Lukasz Piszczek',0,'Poland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (585,'Kamil Glik',0,'Poland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (586,'Michal Pazdan',0,'Poland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (587,'Thiago Cionek',0,'Poland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (588,'Bartosz Bereszynski',0,'Poland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (589,'Artur Jedrzejczyk',0,'Poland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (590,'Maciej Rybus',0,'Poland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (591,'Jakub Blaszczykowski',0,'Poland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (592,'Kamil Grosicki',0,'Poland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (593,'Grzegorz Krychowiak',0,'Poland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (594,'Krzysztof Maczynski',0,'Poland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (595,'Piotr Zielinski',0,'Poland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (596,'Karol Linetty',0,'Poland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (597,'Robert Lewandowski',0,'Poland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (598,'Lukasz Teodorczyk',0,'Poland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (599,'Arkadiusz Milik',0,'Poland','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (600,'Logo Senegal',0,'Senegal','Especial')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (601,'Team Senegal',0,'Senegal','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (602,'Khadim N Diaye',0,'Senegal','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (603,'Kara Mbodji',0,'Senegal','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (604,'Lamine Gassama',0,'Senegal','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (605,'Kalidou Koulibaly',0,'Senegal','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (606,'Salif Sane',0,'Senegal','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (607,'Saliou Ciss',0,'Senegal','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (608,'Moussa Wague',0,'Senegal','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (609,'Idrissa Gueye',0,'Senegal','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (610,'Cheikhou Kouyate',0,'Senegal','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (611,'Cheikh Ndoye',0,'Senegal','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (612,'Pape Alioune N Diaye',0,'Senegal','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (613,'Sadio Mane',0,'Senegal','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (614,'Moussa Sow',0,'Senegal','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (615,'Moussa Konate',0,'Senegal','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (616,'Keita Balde',0,'Senegal','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (617,'M Baye Niang',0,'Senegal','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (618,'Ismaila Sarr',0,'Senegal','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (619,'Mame Diouf',0,'Senegal','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (620,'Logo Colombia',0,'Colombia','Especial')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (621,'Team Colombia',0,'Colombia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (622,'David Ospina',0,'Colombia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (623,'Cristian Zapata',0,'Colombia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (624,'Santiago Arias',0,'Colombia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (625,'Frank Fabra',0,'Colombia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (626,'Davinson Sanchez',0,'Colombia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (627,'Yerry Mina',0,'Colombia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (628,'Carlos Sanchez',0,'Colombia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (629,'Juan Guillermo Cuadrado',0,'Colombia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (630,'Abel Aguilar',0,'Colombia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (631,'James Rodriguez',0,'Colombia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (632,'Giovanni Moreno',0,'Colombia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (633,'Wílmar Barrios',0,'Colombia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (634,'Radamel Falcao Garcia',0,'Colombia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (635,'Teófilo Gutierrez',0,'Colombia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (636,'Carlos Bacca',0,'Colombia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (637,'Edwin Cardona',0,'Colombia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (638,'Yimmi Chara',0,'Colombia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (639,'Duvan Zapata',0,'Colombia','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (640,'Logo Japan',0,'Japan','Especial')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (641,'Team Japan',0,'Japan','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (642,'Eiji Kawashima',0,'Japan','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (643,'Shusaku Nishikawa',0,'Japan','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (644,'Masato Morishige',0,'Japan','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (645,'Yuto Nagatomo',0,'Japan','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (646,'Hiroki Sakai',0,'Japan','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (647,'Tomoaki Makino',0,'Japan','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (648,'Gōtoku Sakai',0,'Japan','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (649,'Maya Yoshida',0,'Japan','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (650,'Hotaru Yamaguchi',0,'Japan','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (651,'Shinji Kagawa',0,'Japan','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (652,'Makoto Hasebe',0,'Japan','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (653,'Hiroshi Kiyotake',0,'Japan','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (654,'Keisuke Honda',0,'Japan','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (655,'Takashi Usami',0,'Japan','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (656,'Genki Haraguchi',0,'Japan','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (657,'Shinji Okazaki',0,'Japan','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (658,'Yuya Kubo',0,'Japan','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (659,'Yuya Osako',0,'Japan','Normal')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (660,'Brazil 1958',0,'World Cup Legends','Especial')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (661,'Germany 2014',0,'World Cup Legends','Especial')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (662,'Italy 1982',0,'World Cup Legends','Especial')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (663,'Ururguay 1930',0,'World Cup Legends','Especial')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (664,'Argentina 1986',0,'World Cup Legends','Especial')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (665,'England 1966',0,'World Cup Legends','Especial')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (666,'France 1998',0,'World Cup Legends','Especial')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (667,'Spain 2010',0,'World Cup Legends','Especial')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (668,'Pele (Most Wins) - Brazil',0,'World Cup Legends','Especial')");
        db.execSQL("INSERT INTO " + TABLE_ALBUM+ INSERT_ROW+ " VALUES (669,'Mirolsav Klose (Most Goals) - Germany',0,'World Cup Legends','Especial')");


    }

    @Override
    public void onUpgrade(SQLiteDatabase db, int i, int i1) {
        db.execSQL("DROP TABLE IF EXISTS " + TABLE_ALBUM);
        onCreate(db);
    }

    public List<Figura> getAllFiguras() {
        List<Figura> figuraList = new ArrayList<Figura>();
        // Select All Query
        String selectQuery = "SELECT  * FROM " + TABLE_ALBUM;

        SQLiteDatabase db = this.getWritableDatabase();
        Cursor cursor = db.rawQuery(selectQuery, null);


        if (cursor.moveToFirst()) {
            do {
                Figura figura = new Figura();


                figura.setIdFigura(cursor.getInt(0));
                figura.setNombreFigura(cursor.getString(1));
                figura.setCantidadFigura(cursor.getInt(2));
                figura.setPais(cursor.getString(3));
                figura.setTipo(cursor.getString(4));

                figuraList.add(figura);
            } while (cursor.moveToNext());
        }


        return figuraList;
    }

}
